add_newline = true
command_timeout = 200
format = """[$directory$git_branch$git_status$git_commit]($style)
$character"""
right_format = "$time$cmd_duration$status$jobs"

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
truncation_length = 5
truncation_symbol = "..."
repo_root_style = "bold green"
style = "bold green"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "italic cyan"
symbol = ' '

[git_commit]
commit_hash_length = 7
tag_symbol = "  "
format = "[\\[$hash$tag\\]]($style) "
style = 'bold green'
only_detached = false
tag_disabled = false
disabled = false

[git_status]
format     = '[$all_status]($style)'
style      = "bold red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = "! "
stashed    = "* "
staged     = "+ "
renamed    = "» "
deleted    = "✘ "
ignore_submodules = false

[time]
format = ' [$time]($style) '
style = 'bold cyan'
time_format = '%T'
disabled = false

[status]
symbol = "[✗](bold red)"
success_symbol = "[](bold green)"
format = '$symbol $status '
map_symbol = false
recognize_signal_code = true
disabled = false

[jobs]
symbol = '+'
number_threshold = 1
symbol_threshold = 1

[cmd_duration]
format = "[$duration]($style) "

