add_newline = true
command_timeout = 200
format = "[$localip$jobs$hostname$directory]($style)$character"
right_format = "$git_branch$git_status$git_commit$time$cmd_duration$status"

[character]
success_symbol = '[â¯](bold green) '
error_symbol = '[â¯](bold red) '

[status]
symbol = "[âœ—](bold red)"
success_symbol = "[ï€Œ](bold green)"
format = '$symbol $status '
map_symbol = true
recognize_signal_code = true
disabled = false

[directory]
truncation_length = 2
truncation_symbol = ""
repo_root_style = "bold green"
style = "bold green"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "italic cyan"
symbol = 'î‚  '

[git_commit]
commit_hash_length = 7
format = '[$hash$tag$tag]($style)'
style = 'bold green'
only_detached = false
disabled = false

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[cmd_duration]
format = "[$duration]($style) "

[hostname]
ssh_only = true
ssh_symbol = 'ğŸŒ '
format = '[$ssh_symbol](bold blue)'
disabled = false

[jobs]
symbol = '+ '
number_threshold = 1
symbol_threshold = 1

[localip]
ssh_only = true
format = '[$localipv4](bold red) '
disabled = false

[time]
disabled = false
format = ' $time$style '
time_format = '%T'
